name: Build & Release

on:
  push:
    tags:
      - 'v*'        # trigger when you push tags like v1.0.0

jobs:
  build_release:
    runs-on: windows-latest
    permissions:
      contents: write   # needed to create/edit releases

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # need full history for changelog

      - name: Get version from tag
        id: ver
        shell: bash
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Generate changelog since previous tag
        id: changelog
        shell: bash
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 --match "v*" --always $(git rev-list --tags --skip=1 --max-count=1))
          if [ -z "$PREV_TAG" ]; then PREV_TAG=$(git rev-list --max-parents=0 HEAD); fi
          echo "Changes since $PREV_TAG:" > CHANGELOG.md
          git log --pretty=format:"- %s (%h)" $PREV_TAG..HEAD >> CHANGELOG.md
          {
            echo "body<<'EOF'"
            cat CHANGELOG.md
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole --name MTU_Finder mtufinder.py

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: MTU_Finder.exe
          path: dist/MTU_Finder.exe

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.body }}
          files: dist/MTU_Finder.exe
