name: Build & (maybe) Release

on:
  push:
    branches: [ main ]
    tags:     [ 'v*' ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prep env vars
        shell: bash
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "NIGHTLY_TAG=nightly-${GITHUB_RUN_NUMBER}-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Generate changelog (only on tag)
        if: github.ref_type == 'tag'
        shell: bash
        run: |
          CUR_TAG="${GITHUB_REF_NAME}"
          PREV_TAG=$(git describe --tags --abbrev=0 --match "v*" "${CUR_TAG}^" 2>/dev/null || true)
          if [ -z "$PREV_TAG" ]; then PREV_TAG=$(git rev-list --max-parents=0 HEAD); fi
          echo "Changes since $PREV_TAG:" > CHANGELOG.md
          git log --pretty=format:"- %s (%h)" $PREV_TAG..$CUR_TAG >> CHANGELOG.md

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Nuitka
        run: python -m pip install --upgrade nuitka ordered-set zstandard

      - name: Build with Nuitka
        shell: bash
        env:
          NUITKA_ASSUME_YES_FOR_DOWNLOADS: "1"
        run: |
          VER="0.0.0"
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then VER="${GITHUB_REF_NAME#v}"; fi

          python -m nuitka \
            --onefile \
            --windows-console-mode=disable \
            --mingw64 \
            --assume-yes-for-downloads \
            --enable-plugin=tk-inter \
            --windows-file-version="$VER" \
            --windows-product-version="$VER" \
            --windows-company-name="Soham Sen" \
            --windows-product-name="WireGuard MTU Finder" \
            --output-filename=MTU_Finder.exe \
            mtufinder.py

      - uses: actions/upload-artifact@v4
        with:
          name: MTU_Finder.exe
          path: MTU_Finder.exe
          compression-level: 0

      - name: Publish nightly prerelease (unique tag each push)
        if: github.ref_type == 'branch'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.NIGHTLY_TAG }}
          name: ${{ env.NIGHTLY_TAG }}
          prerelease: true
          allowUpdates: false
          artifacts: MTU_Finder.exe

      - name: Publish tagged release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path: CHANGELOG.md
          files: MTU_Finder.exe
